### ISSUE TITLE
Circular import

### ISSUE THREAD

**Issue by eliedrian** [tomduck/pandoc-latex-extensions#4]
All I get is this when running `pandoc` with this filter on.

```
Traceback (most recent call last):
  File "/home/tan/.local/bin/pandoc-latex-extensions", line 5, in <module>
    from pandoclatexextensions import main
  File "/home/tan/.local/lib/python3.8/site-packages/pandoclatexextensions/__init__.py", line 2, in <module>
    from .core import *
  File "/home/tan/.local/lib/python3.8/site-packages/pandoclatexextensions/core.py", line 33, in <module>
    from . import plugins
ImportError: cannot import name 'plugins' from partially initialized module 'pandoclatexextensions' (most likely due to a circular import) (/home/tan/.local/lib/python3.8/site-packages/pandoclatexextensions/__init__.py)
Error running filter pandoc-latex-extensions:
Filter returned error status 1
```

**Comment by eliedrian** [comment]
Apparently installing with `pip` didn't bring in the `plugins` folder? Copying what I needed (`epigraph.py`) from this repo to my `plugins` folder under `site-packages` worked.

Curious.

**Comment by relikd** [comment]
Thanks @eliedrian, that fixed the issue. But now I face another one, did you have the same or is it my configuration?

```
% pandoc --filter pandoc-latex-extensions -o content.html content.tex

pandoc-latex-extensions: Wrote the following blocks to header-
includes.  If you use pandoc's  --include-in-header option then you
will need to  manually include these yourself.
Error running filter pandoc-latex-extensions:
Error in $: endOfInput
```

(and does this extension even work for the tex->html direction?)

**Comment by rtbs-dev** [comment]
Tested, hopefully solved with PR #6 . Works on my end (try `pip install git+https://github.com/tbsexton/pandoc-latex-extensions.git@patch-1` to try it out on your side...since the version number wasn't changed, make sure to `pip uninstall pandoc-latex-extensions` first!).
